# Generated by Django 5.2.7 on 2026-06-17 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_patientprofile_gender_doctorapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_duration',
            field=models.PositiveIntegerField(default=20, help_text='Daqiqada'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hospital', 'Shifohona'), ('doctor', 'Shifokor'), ('patient', 'Bemor')], default='patient', max_length=10),
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='my_app.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shifohona profili',
                'verbose_name_plural': 'Shifohona profillari',
            },
        ),
    ]
