# Generated by Django 5.2.7 on 2026-08-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_doctorapplication_reject_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reminder', '1 soat qoldi'), ('confirmed', 'Navbat tasdiqlandi'), ('cancelled', 'Navbat bekor qilindi'), ('completed', 'Qabul tugadi'), ('no_show', 'Bemor kelmadi'), ('new_application', "Yangi shifokor so'rovi")], max_length=15),
        ),
    ]